version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: admin-panel-frontend
    environment:
      - NODE_ENV=production
    ports:
      - "3004:80"
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 